### ISSUE TITLE
小米手机角标问题

### ISSUE THREAD

**Issue by 2318423730** [l123456789jy/Lazy#12]
程序有推送功能，本来就要弹出通知栏，控制角标，miui又强行显示一个通知栏，这怎么弄

**Comment by l123456789jy** [comment]
@2318423730 
没理解你的意思

**Comment by 2318423730** [comment]
就现在我的程序来说，本来集成了融云的第三方用于聊天，在收到信息后，融云会主动弹出通知栏，但是会显示角标的手机上，角标永远是1，所以我之前想自己去修改角标值。 但是小米的miui修改角标又和通知栏关联，人家融云本来就弹出通知栏了,我要去改角标，岂不是又要弹出一个通知栏

**Comment by 2318423730** [comment]
所以这个没有什么思路去解决呀

**Comment by l123456789jy** [comment]
@2318423730 
小米手机都自带的有角标通知没必要在搞了。
