### ISSUE TITLE
BitMapUtil里有一个方法有问题

### ISSUE THREAD

**Issue by eling13** [l123456789jy/Lazy#5]
getBitmapFromStream(InputStream is, Rect outPadding, int reqWidth, int reqHeight)
{
  ...
  BitmapFactory.decodeStream(is, outPadding, options);
  options = calculateInSampleSize(options, reqWidth, reqHeight);
  return BitmapFactory.decodeStream(is, outPadding, options);
}
对流的读取只有一次，读取第二次的时候返回的是null的。

**Comment by l123456789jy** [comment]
好的，我看下。
